# Up-to-date with SCSS-Lint v0.50

scss_files: "**/*.scss"

exclude:
  - "vendor/**/*.scss"
  - "node_modules/**/*.scss"

severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 2

  BorderZero:
    enabled: true
    convention: zero

  ChainedClasses:
    enabled: true

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    style: silent

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: false

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true
    ignore_consecutive:
      - background
      - transition

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero

  LengthVariable:
    enabled: false

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: false

  PropertyCount:
    enabled: false

  PropertySortOrder:
    enabled: true
    ignore_unspecified: true
    min_properties: 2
    separate_groups: true
    order:
      - content
      - quotes
      - display
      - visibility
      - position
      - z-index
      - top
      - right
      - bottom
      - left
      - box-sizing
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - align-content
      - align-items
      - align-self
      - justify-content
      - order
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - float
      - clear
      - overflow
      - overflow-x
      - overflow-y
      - clip
      - zoom
      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width
      - table-layout
      - empty-cells
      - caption-side
      - border-spacing
      - border-collapse
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      - transform
      - transform-origin
      - transform-style
      - backface-visibility
      - perspective
      - perspective-origin
      - transition
      - transition-property
      - transition-duration
      - transition-timing-function
      - transition-delay
      - animation
      - animation-name
      - animation-duration
      - animation-play-state
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      - stroke-width
      - stroke-linecap
      - stroke-dasharray
      - stroke-dashoffset
      - stroke
      - opacity
      - background
      - background-color
      - background-image
      - background-repeat
      - background-position
      - background-size
      - box-shadow
      - fill
      - color
      - font
      - font-family
      - font-size
      - font-size-adjust
      - font-stretch
      - font-effect
      - font-style
      - font-variant
      - font-weight
      - font-emphasize
      - font-emphasize-position
      - font-emphasize-style
      - letter-spacing
      - line-height
      - list-style
      - word-spacing
      - text-align
      - text-align-last
      - text-decoration
      - text-indent
      - text-justify
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-rendering
      - text-outline
      - text-shadow
      - text-transform
      - text-wrap
      - word-wrap
      - word-break
      - text-emphasis
      - text-emphasis-color
      - text-emphasis-style
      - text-emphasis-position
      - vertical-align
      - white-space
      - word-spacing
      - hyphens
      - src
      - tab-size
      - counter-reset
      - counter-increment
      - resize
      - cursor
      - pointer-events
      - speak
      - user-select
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left

  PropertySpelling:
    enabled: true
    extra_properties:
      - text-decoration-skip
    disabled_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q',
      'vh', 'vw', 'vmin', 'vmax',
      'deg', 'grad', 'rad', 'turn',
      'ms', 's',
      'Hz', 'kHz',
      'dpi', 'dpcm', 'dppx',
      '%']
    properties:
      line-height: []

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: false

  SpaceAfterComma:
    enabled: true
    style: one_space

  SpaceAfterComment:
    enabled: true
    style: at_least_one_space
    allow_empty_comments: true

  SpaceAfterPropertyColon:
    enabled: true
    style: at_least_one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true
    style: one_space

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true
    properties:
      - color
      - background-color
      - font

  VendorPrefix:
    enabled: true
    identifier_list: base

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false