fail_on_violations: true

ruby:
  config_file: /ruby/.rubocop.yml

scss:
  config_file: /scss/.scss-lint.yml
  exclude:
    - "vendor/**/*.scss"
    - "node_modules"

coffeescript:
  config_file: /coffeescript/.coffee-lint.json

jshint:
  config_file: /javascript/.jshintrc
  exclude:
    - "public"
    - "vendor"
    - "node_modules"

haml:
  config_file: /haml/.haml-lint.yml

swift:
  config_file: /swift/.swift-lint.yml
